# Prometheus Configuration for LinkedIn Automation Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files for alerts
rule_files:
  - "/etc/prometheus/rules/*.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # LinkedIn Automation Application Metrics
  - job_name: 'linkedin-automation'
    static_configs:
      - targets: ['linkedin-automation:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    
    # Custom labels for identification
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'linkedin-automation'
      - source_labels: []
        target_label: service
        replacement: 'linkedin-automation'

  # System metrics from node exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'production-server'

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # SSL certificate monitoring
  - job_name: 'ssl-exporter'
    static_configs:
      - targets: ['ssl-exporter:9219']
    scrape_interval: 300s  # 5 minutes
    
    params:
      target: ['https://your-domain.com:443']

  # Blackbox monitoring for external endpoints
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.linkedin.com/v2
        - https://www.linkedin.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint/"
#     basic_auth:
#       username: "username"
#       password: "password"

# Storage configuration
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB