[project]
name = "synapse-rag"
version = "0.1.0"
description = "A Graph-Enhanced RAG implementation using Memgraph and modern Python"
authors = [
    {name = "Your Name", email = "your.email@example.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.6.1",
    "fastapi>=0.109.2",
    "uvicorn[standard]>=0.27.1",
    "neo4j>=5.14.1",
    "python-dotenv>=1.0.0",
    "httpx[cli]>=0.26.0",
    "typing-extensions>=4.9.0",
    "sentence-transformers>=2.2.2",
    "pydantic-settings>=2.1.0",
    "tenacity>=8.2.3",
    "spacy>=3.7.0",
    "numpy",
    "scikit-learn",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-asyncio>=0.23.5",
    "pytest-cov>=4.1.0",
    "pytest-mock>=3.12.0",
    "pytest-xdist>=3.5.0",
    "ruff>=0.2.1",
    "black>=24.1.1",
    "mypy>=1.8.0",
    "pre-commit>=3.6.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["graph_rag"]

[tool.ruff]
line-length = 88
target-version = "py311"
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF", "ANN", "S", "TCH"]
ignore = []
unfixable = ["ANN", "TCH"]

[tool.ruff.isort]
known-first-party = ["graph_rag"]
combine-as-imports = true
force-single-line = false

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_optional = true
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_any_unimported = true
disallow_any_expr = true
disallow_any_decorated = true
disallow_any_explicit = true
no_implicit_reexport = true

[[tool.mypy.overrides]]
module = ["tests.*"]
disallow_untyped_defs = false
disallow_incomplete_defs = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=graph_rag --cov-report=term-missing -n auto"
markers = [
    "asyncio: mark test as async",
    "integration: mark test as integration test",
    "slow: mark test as slow"
]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::UserWarning"
] 
