name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pipx install uv
      - name: Install deps
        run: uv pip install -e .[dev]
      - name: Lint
        run: uv run ruff check .
      - name: Format check
        run: uv run ruff format --check .
      - name: Unit tests
        run: make test
      - name: Coverage (hot paths)
        run: make coverage-hot

  memgraph-integration:
    if: contains(github.event.pull_request.labels.*.name, 'memgraph')
    runs-on: ubuntu-latest
    services:
      memgraph:
        image: memgraph/memgraph:latest
        ports:
          - 7687:7687
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        run: pipx install uv
      - name: Install deps
        run: uv pip install -e .[dev]
      - name: Wait for Memgraph
        run: |
          for i in {1..30}; do
            echo "Checking Memgraph... attempt $i"
            nc -z 127.0.0.1 7687 && echo "Memgraph is up" && exit 0
            sleep 2
          done
          echo "Memgraph failed to start" && exit 1
      - name: Run integration tests
        env:
          TEST_MEMGRAPH_URI: bolt://127.0.0.1:7687
          TEST_NEO4J_URI: bolt://127.0.0.1:7687
          TEST_NEO4J_USER: neo4j
          TEST_NEO4J_PASSWORD: password
        run: make test-integration
