name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip
      - name: Install deps (dev)
        run: |
          pip install -e .[dev]
      - name: Lint
        run: |
          ruff check .
      - name: Run unit tests
        env:
          SKIP_SPACY_IMPORT: '1'
          GRAPH_RAG_EMBEDDING_PROVIDER: 'mock'
          GRAPH_RAG_LLM_TYPE: 'mock'
        run: |
          pytest -m "not integration" -q
